# Generated by Django 3.0.2 on 2020-02-18 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BomFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled', max_length=50)),
                ('number_of_items', models.PositiveIntegerField(blank=True, default=1)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bom_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BomFile',
                'verbose_name_plural': 'BomFiles',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='MastFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled', max_length=50)),
                ('number_of_items', models.PositiveIntegerField(blank=True, default=1)),
                ('planning_horizon_length', models.PositiveIntegerField(blank=True, default=0)),
                ('number_time_buckets', models.PositiveIntegerField(blank=True, default=0)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mast_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MastFile',
                'verbose_name_plural': 'MastFiles',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(blank=True, max_length=12, null=True)),
                ('data', models.CharField(blank=True, max_length=20, null=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='mrp.MastFile')),
            ],
            options={
                'verbose_name': 'Master Schedule',
                'verbose_name_plural': 'Masters Schedules',
                'ordering': ['file', 'part_number', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(blank=True, max_length=12, null=True)),
                ('tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('parent', models.CharField(blank=True, max_length=12, null=True)),
                ('qty', models.PositiveIntegerField(blank=True, default=1)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mrp.BomFile')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['part_number'],
            },
        ),
    ]
