# Generated by Django 3.0.2 on 2020-02-18 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(default='Untitled', max_length=50),
        ),
    ]
