# Generated by Django 3.0.2 on 2020-02-07 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrp.Item'),
        ),
        migrations.AddField(
            model_name='item',
            name='qty',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
