# Generated by Django 3.0.2 on 2020-02-21 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bomfile',
            options={'ordering': ['-created_date', 'title'], 'verbose_name': 'BomFile', 'verbose_name_plural': 'BomFiles'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['id'], 'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelOptions(
            name='mastfile',
            options={'ordering': ['-created_date', 'title'], 'verbose_name': 'MastFile', 'verbose_name_plural': 'MastFiles'},
        ),
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['file', 'part_number', 'order'], 'verbose_name': 'Period', 'verbose_name_plural': 'Periods'},
        ),
    ]
