# Generated by Django 3.0.3 on 2020-02-18 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0002_auto_20200217_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(blank=True, max_length=12, null=True)),
                ('data', models.CharField(blank=True, max_length=20, null=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masters_schedules', to='mrp.File')),
            ],
            options={
                'verbose_name': 'Master Schedule',
                'verbose_name_plural': 'Masters Schedules',
                'ordering': ['file', 'part_number', 'order'],
            },
        ),
        migrations.DeleteModel(
            name='MasterSchedule',
        ),
    ]
