# Generated by Django 3.0.2 on 2020-02-21 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0002_auto_20200221_1605'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='period',
            unique_together={('file', 'part_number', 'order')},
        ),
    ]
