# Generated by Django 3.0.2 on 2020-02-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0002_auto_20200206_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='parent',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
