# Generated by Django 3.0.2 on 2020-03-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0003_auto_20200307_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitem',
            name='order',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='order',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
