# Generated by Django 3.0.3 on 2020-03-04 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0003_auto_20200304_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmaster',
            name='carrying_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='invitem',
            name='on_hand',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invitem',
            name='past_due',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invitem',
            name='safe_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='demand',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='lead_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='multiple',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='order_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='unit_value',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='yield_percent',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
