# Generated by Django 3.0.3 on 2020-03-05 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0004_auto_20200304_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmaster',
            name='clase',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_masters', to='mrp.ItemMasterFile'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='lot_size',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
    ]
