# Generated by Django 3.0.2 on 2020-02-10 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0004_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mrp.File'),
            preserve_default=False,
        ),
    ]
