# Generated by Django 3.0.2 on 2020-03-08 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0004_auto_20200308_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitem',
            options={'ordering': ['file', 'order'], 'verbose_name': 'InvItem', 'verbose_name_plural': 'InvItems'},
        ),
        migrations.AlterModelOptions(
            name='itemmaster',
            options={'ordering': ['file', 'order'], 'verbose_name': 'ItemMaster', 'verbose_name_plural': 'ItemMasters'},
        ),
    ]
