# Generated by Django 3.0.2 on 2020-03-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0005_auto_20200308_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mastitem',
            options={'ordering': ['file', 'order'], 'verbose_name': 'MastItem', 'verbose_name_plural': 'MastItems'},
        ),
        migrations.AddField(
            model_name='mastitem',
            name='order',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
