# Generated by Django 3.0.2 on 2020-02-12 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0007_auto_20200211_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='order',
        ),
    ]
