# Generated by Django 3.0.2 on 2020-03-09 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0007_bomfile_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='invfile',
            name='removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemmasterfile',
            name='removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mastfile',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
