# Generated by Django 3.0.2 on 2020-03-09 00:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0008_auto_20200308_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmaster',
            name='yield_percent',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
    ]
