# Generated by Django 3.0.2 on 2020-03-11 01:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0010_auto_20200310_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastitem',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
