# Generated by Django 3.0.2 on 2020-03-11 01:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0011_auto_20200310_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomitem',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='invitem',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
